### PR TITLE
Jesse/toggle map

### PR DESCRIPTION
**Pull request by ChenJesse**
Partial solution to issue #53, brings up MKMapView of eatery location

### CODE REVIEW

**Comment by lucasderraugh** [comment]
Ideally we would self contain this in it's own VC. I'm ok with this being merged but if you'd like to work on it more that would be good too. 2 main things that stick out to me:
1. Let's start using callbacks instead of delegates when applicable.
2. Make the map view be a self contained VC that can dismiss itself on the button tap. Otherwise the MenuVC takes on that responsibility which is really not the place for it.

**Comment by ChenJesse** [comment]
Made the changes you asked for.

**Comment by lucasderraugh** [comment]
Merged in 2694e81

**Comment by lucasderraugh** [comment]
@ChenJesse Just might want to note some of the dependency injection added to the class. The inits are ugly within the class, but because the class requires that eatery, it's nicer to inject the eatery object directly. You can initialize all the other objects ahead of time guaranteeing their existence instead of implicitly unwrapping them.

**Pull request closed without merging**
