### PR TITLE
Fixed some UI bugs

### PR DESCRIPTION
**Pull request by arman-esmaili**
MenuViewController: fixed pageViewController frame
LookAhead: fixed days of the week

### CODE REVIEW

**Comment by anniexcheng** [comment]
Looks good!

**Comment by dantheli** [comment]
Nice job with the scroll view for the menu's, but this seems to break the open indicators when the cells are initially loaded. Let's fix that and then merge.

**Comment by arman-esmaili** [comment]
Everything should look the same as 1.0.3 now

**Comment by dantheli** [comment]
Awesome work! I'll merge this into my branch, and shortly after we can merge into master.

**Pull request merged**
