### PR TITLE
Properly handles unlimited meal swipes

### PR DESCRIPTION
**Pull request by arman-esmaili**
Let me know if this fixes the bug

### CODE REVIEW

**Comment by anniexcheng** [comment]
@myo3 @dantheli can you test this on your phone since you have unlimited meal swipes?

**Comment by myo3** [comment]
@acheng96 herm getting some errors when trying to run it on my phone (Add your developer account to Xcode:  There are no accounts registered with Xcode,
No profiles for 'org.cuappdev.eatery.watchkitapp.watchkitextension' were found:  Xcode couldn't find a provisioning profile matching 'org.cuappdev.eatery.watchkitapp.watchkitextension'.
Code signing is required for product type 'WatchKit Extension' in SDK 'watchOS 3.1'). I tried adding my personal icloud account as a developer, but I still got errors (Failed to create provisioning profile.
The app ID "org.cuappdev.eatery" cannot be registered to your development team. Change your bundle identifier to a unique string to try again, No profiles for 'org.cuappdev.eatery' were found
Xcode couldn't find a provisioning profile matching 'org.cuappdev.eatery'). I can try during the meeting?

**Comment by dennisfedorko** [comment]
@myo3 need to sign in using our team provisioning profile

**Comment by myo3** [comment]
@dennisfedorko Thanks! I got it running on my phone

@acheng96 Works on my iPhone (says unlimited) 👍

Minor thing: In BRBController I had to change 
`if error == BRBConnectionHandler.Stages.updateProfile.toString() {`to `if error == BRBConnectionHandler.Stages.updateProfile.rawValue {`, and also for the `Stages` enum I made it a string enum (`enum Stages: String {`), for it to compile.

**Pull request merged**
